apiVersion: v1
kind: Service
metadata:
  name: spaceinvaders-clusterip
  namespace: default
  labels:
    app: spaceinvaders-clusterip
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 80
  selector:
    app: spaceinvaders
  type: ClusterIP
